#!/bin/ash

start() {
    ifconfig mlan0 192.168.1.1 netmask 255.255.255.0 up
    iwconfig mlan0 power off
    sleep 2
}

stop() {
    true
}

case "$1" in
    stop) stop ;;
    start) start ;;
    restart) stop ; start ;;
    *) echo "Usage: "$0" {start|stop|restart}" ; exit 1
esac
 
exit $?
